### ISSUE TITLE
Issue with testing when using getenv() instead of superglobal variable.

### ISSUE THREAD

**Issue by KevinDonaldson** [mattwellss/magento-composer-autoloader#8]
I believe this is because of the function testRegisterWithEnv() setting the superglobal $_ENV but in my environment it should be $_SERVER.

**Comment by mattwellss** [comment]
Looks like `$_SERVER` is set correctly with variables that are `export`ed on CLI and will work correctly for variables that are `SetEnv`ed (in Apache, for instance).
Fixed in 4be8a918dece620eb7e0297fd8e6d95a6aa203f3
